name: Deploy Bot to Server and start

on:
  pull_request:
    branches:
      - main
# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: runner

      - name: Pull latest changes on the server
        run: |
          cd runner
          pwd
          git pull origin main

      - name: Install dependencies
        run: npm install

      - name: Restart Telegram bot
        run: |
          pm2 stop bot
          pm2 start src/index.js --name bot
