name: Deploy Bot to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes on the server
        run: git pull origin main

      - name: Install dependencies
        run: npm install

      - name: Restart Telegram bot
        run: |
          pm2 stop bot
          pm2 start src/index.js --name bot
