name: Deploy Bot to Server and start

on:
  pull_request:
    branches:
      - main

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: runner

      - name: Create backup .env file
        run: cp ../../../../projects/arbisyt-infinite/.env .env.backup

      - name: Pull latest changes on the server
        run: |
          cd runner
          forever stop index.js
          env
          git fetch origin
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          cd runner
          npm install

      - name: Restart Telegram bot
        run: |
          cd runner
          forever start index.js
