name: Deploy Bot to Server and start

on:
  pull_request:
    branches:
      - main

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: runner

      - name: Create backup .env file
        run: cp ../../../../projects/arbisyt-infinite/.env .env.backup

      - name: Pull latest changes on the server
        run: |
          cd runner
          env
          git fetch origin
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          cd runner
          npm install

      - name: Set environment variables
        run: |
          cd runner
          echo "TELEGRAM_BOT_KEY=${{ secrets.TELEGRAM_BOT_KEY }}" >> .env
          echo "BINANCE_KEY=${{ secrets.BINANCE_KEY }}" >> .env
          echo "BINANCE_SECRET=${{ secrets.BINANCE_SECRET }}" >> .env
          cat .env

      - name: Restart Telegram bot
        run: |
          cd runner
          cat .env
          nodemon /index.js --name bot
